### ISSUE TITLE
Performance Roadmap

### ISSUE THREAD

**Issue by SimonDanisch** [JuliaGL/GLAbstraction.jl#54]
- [ ] We need to unrole [this loop](https://github.com/JuliaGL/GLAbstraction.jl/blob/master/src/GLRender.jl#L29) for optimal performance
- [ ] In the same loop, it would be great to diff against the previously rendered primitive, to reduce draw calls
- [ ] even better: bake drawcalls for each program and move the entire loop to the GPU
- [ ] Use one big buffer and distribute only views into that buffer

**Comment by PallHaraldsson** [comment]
[Assuming "unroll"]

Maybe you already know of:

https://github.com/StephenVavasis/Unroll.jl
